apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingkaro-hpa
  namespace: shopingkaro
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingkaro
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
